<?xml version="1.0" encoding="utf-8"?><Database Name="mi" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=pc\SQLEXPRESS;Initial Catalog=mi;User ID=sa" SettingsObjectName="ConsoleApplication2.Properties.Settings" SettingsPropertyName="miConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DATAENTRY" Member="DATAENTRies">
    <Type Name="DATAENTRY">
      <Column Name="AWBNO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BKDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DEST" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CLCODE" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="CONSIGNEE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CNEADDRESS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="BMODE" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="MMODE" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="PKGS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BWT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MWT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PMODE" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="AMOUNT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="POD_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="POD_TIME" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BILLNO" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="network" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="destination" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="clname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tdesc" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tamt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ntdesc" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ntamt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="famt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fcode" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="adsns" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NETNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dlvboy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mainbilno" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BRANCH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MFNO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MFDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MFWD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Actualdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="upload" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Shpchrg" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dtdamt" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="zone" Type="System.String" DbType="Char(3)" CanBeNull="true" />
    </Type>
  </Table>
</Database>