#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mi")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::ConsoleApplication2.Properties.Settings.Default.miConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DATAENTRY> DATAENTRies
		{
			get
			{
				return this.GetTable<DATAENTRY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATAENTRY")]
	public partial class DATAENTRY
	{
		
		private string _AWBNO;
		
		private System.Nullable<System.DateTime> _BKDATE;
		
		private string _DEST;
		
		private string _CLCODE;
		
		private string _CONSIGNEE;
		
		private string _CNEADDRESS;
		
		private string _TYPE;
		
		private string _BMODE;
		
		private string _MMODE;
		
		private System.Nullable<short> _PKGS;
		
		private System.Nullable<double> _BWT;
		
		private System.Nullable<double> _MWT;
		
		private string _PMODE;
		
		private System.Nullable<double> _AMOUNT;
		
		private System.Nullable<System.DateTime> _POD_DATE;
		
		private string _POD_TIME;
		
		private string _STATUS;
		
		private string _REMARKS;
		
		private string _USERNAME;
		
		private System.Nullable<decimal> _BILLNO;
		
		private string _network;
		
		private string _destination;
		
		private string _clname;
		
		private string _tdesc;
		
		private System.Nullable<double> _tamt;
		
		private string _ntdesc;
		
		private System.Nullable<double> _ntamt;
		
		private string _fname;
		
		private System.Nullable<double> _famt;
		
		private string _fcode;
		
		private System.Nullable<double> _adsns;
		
		private string _state;
		
		private string _NETNO;
		
		private string _dlvboy;
		
		private string _mainbilno;
		
		private string _BRANCH;
		
		private string _MFNO;
		
		private System.Nullable<System.DateTime> _MFDATE;
		
		private string _MFWD;
		
		private System.Nullable<System.DateTime> _Actualdate;
		
		private System.Nullable<char> _upload;
		
		private System.Nullable<double> _Shpchrg;
		
		private System.Nullable<double> _dtdamt;
		
		private string _zone;
		
		public DATAENTRY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWBNO", DbType="VarChar(20)")]
		public string AWBNO
		{
			get
			{
				return this._AWBNO;
			}
			set
			{
				if ((this._AWBNO != value))
				{
					this._AWBNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BKDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> BKDATE
		{
			get
			{
				return this._BKDATE;
			}
			set
			{
				if ((this._BKDATE != value))
				{
					this._BKDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEST", DbType="VarChar(20)")]
		public string DEST
		{
			get
			{
				return this._DEST;
			}
			set
			{
				if ((this._DEST != value))
				{
					this._DEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLCODE", DbType="VarChar(6)")]
		public string CLCODE
		{
			get
			{
				return this._CLCODE;
			}
			set
			{
				if ((this._CLCODE != value))
				{
					this._CLCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSIGNEE", DbType="VarChar(50)")]
		public string CONSIGNEE
		{
			get
			{
				return this._CONSIGNEE;
			}
			set
			{
				if ((this._CONSIGNEE != value))
				{
					this._CONSIGNEE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNEADDRESS", DbType="VarChar(100)")]
		public string CNEADDRESS
		{
			get
			{
				return this._CNEADDRESS;
			}
			set
			{
				if ((this._CNEADDRESS != value))
				{
					this._CNEADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Char(2)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMODE", DbType="Char(2)")]
		public string BMODE
		{
			get
			{
				return this._BMODE;
			}
			set
			{
				if ((this._BMODE != value))
				{
					this._BMODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MMODE", DbType="Char(2)")]
		public string MMODE
		{
			get
			{
				return this._MMODE;
			}
			set
			{
				if ((this._MMODE != value))
				{
					this._MMODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKGS", DbType="SmallInt")]
		public System.Nullable<short> PKGS
		{
			get
			{
				return this._PKGS;
			}
			set
			{
				if ((this._PKGS != value))
				{
					this._PKGS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BWT", DbType="Float")]
		public System.Nullable<double> BWT
		{
			get
			{
				return this._BWT;
			}
			set
			{
				if ((this._BWT != value))
				{
					this._BWT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MWT", DbType="Float")]
		public System.Nullable<double> MWT
		{
			get
			{
				return this._MWT;
			}
			set
			{
				if ((this._MWT != value))
				{
					this._MWT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMODE", DbType="Char(2)")]
		public string PMODE
		{
			get
			{
				return this._PMODE;
			}
			set
			{
				if ((this._PMODE != value))
				{
					this._PMODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT", DbType="Float")]
		public System.Nullable<double> AMOUNT
		{
			get
			{
				return this._AMOUNT;
			}
			set
			{
				if ((this._AMOUNT != value))
				{
					this._AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> POD_DATE
		{
			get
			{
				return this._POD_DATE;
			}
			set
			{
				if ((this._POD_DATE != value))
				{
					this._POD_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POD_TIME", DbType="VarChar(10)")]
		public string POD_TIME
		{
			get
			{
				return this._POD_TIME;
			}
			set
			{
				if ((this._POD_TIME != value))
				{
					this._POD_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(25)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARKS", DbType="VarChar(50)")]
		public string REMARKS
		{
			get
			{
				return this._REMARKS;
			}
			set
			{
				if ((this._REMARKS != value))
				{
					this._REMARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(20)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this._USERNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BILLNO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> BILLNO
		{
			get
			{
				return this._BILLNO;
			}
			set
			{
				if ((this._BILLNO != value))
				{
					this._BILLNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_network", DbType="VarChar(50)")]
		public string network
		{
			get
			{
				return this._network;
			}
			set
			{
				if ((this._network != value))
				{
					this._network = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination", DbType="VarChar(50)")]
		public string destination
		{
			get
			{
				return this._destination;
			}
			set
			{
				if ((this._destination != value))
				{
					this._destination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clname", DbType="VarChar(50)")]
		public string clname
		{
			get
			{
				return this._clname;
			}
			set
			{
				if ((this._clname != value))
				{
					this._clname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tdesc", DbType="VarChar(100)")]
		public string tdesc
		{
			get
			{
				return this._tdesc;
			}
			set
			{
				if ((this._tdesc != value))
				{
					this._tdesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamt", DbType="Float")]
		public System.Nullable<double> tamt
		{
			get
			{
				return this._tamt;
			}
			set
			{
				if ((this._tamt != value))
				{
					this._tamt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ntdesc", DbType="VarChar(100)")]
		public string ntdesc
		{
			get
			{
				return this._ntdesc;
			}
			set
			{
				if ((this._ntdesc != value))
				{
					this._ntdesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ntamt", DbType="Float")]
		public System.Nullable<double> ntamt
		{
			get
			{
				return this._ntamt;
			}
			set
			{
				if ((this._ntamt != value))
				{
					this._ntamt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(50)")]
		public string fname
		{
			get
			{
				return this._fname;
			}
			set
			{
				if ((this._fname != value))
				{
					this._fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_famt", DbType="Float")]
		public System.Nullable<double> famt
		{
			get
			{
				return this._famt;
			}
			set
			{
				if ((this._famt != value))
				{
					this._famt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fcode", DbType="VarChar(6)")]
		public string fcode
		{
			get
			{
				return this._fcode;
			}
			set
			{
				if ((this._fcode != value))
				{
					this._fcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adsns", DbType="Float")]
		public System.Nullable<double> adsns
		{
			get
			{
				return this._adsns;
			}
			set
			{
				if ((this._adsns != value))
				{
					this._adsns = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(50)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NETNO", DbType="VarChar(50)")]
		public string NETNO
		{
			get
			{
				return this._NETNO;
			}
			set
			{
				if ((this._NETNO != value))
				{
					this._NETNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dlvboy", DbType="VarChar(50)")]
		public string dlvboy
		{
			get
			{
				return this._dlvboy;
			}
			set
			{
				if ((this._dlvboy != value))
				{
					this._dlvboy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mainbilno", DbType="VarChar(50)")]
		public string mainbilno
		{
			get
			{
				return this._mainbilno;
			}
			set
			{
				if ((this._mainbilno != value))
				{
					this._mainbilno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH", DbType="VarChar(50)")]
		public string BRANCH
		{
			get
			{
				return this._BRANCH;
			}
			set
			{
				if ((this._BRANCH != value))
				{
					this._BRANCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MFNO", DbType="VarChar(15)")]
		public string MFNO
		{
			get
			{
				return this._MFNO;
			}
			set
			{
				if ((this._MFNO != value))
				{
					this._MFNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MFDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MFDATE
		{
			get
			{
				return this._MFDATE;
			}
			set
			{
				if ((this._MFDATE != value))
				{
					this._MFDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MFWD", DbType="VarChar(50)")]
		public string MFWD
		{
			get
			{
				return this._MFWD;
			}
			set
			{
				if ((this._MFWD != value))
				{
					this._MFWD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actualdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> Actualdate
		{
			get
			{
				return this._Actualdate;
			}
			set
			{
				if ((this._Actualdate != value))
				{
					this._Actualdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upload", DbType="Char(1)")]
		public System.Nullable<char> upload
		{
			get
			{
				return this._upload;
			}
			set
			{
				if ((this._upload != value))
				{
					this._upload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shpchrg", DbType="Float")]
		public System.Nullable<double> Shpchrg
		{
			get
			{
				return this._Shpchrg;
			}
			set
			{
				if ((this._Shpchrg != value))
				{
					this._Shpchrg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtdamt", DbType="Float")]
		public System.Nullable<double> dtdamt
		{
			get
			{
				return this._dtdamt;
			}
			set
			{
				if ((this._dtdamt != value))
				{
					this._dtdamt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zone", DbType="Char(3)")]
		public string zone
		{
			get
			{
				return this._zone;
			}
			set
			{
				if ((this._zone != value))
				{
					this._zone = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
